# -*- coding: utf-8 -*-
"""Copy_of_swin_unetr_brats21_segmentation_3d (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M9mR1d23Gs77NRAOzvJOPWTu2R9PJv4f
"""



"""Copyright (c) MONAI Consortium  
Licensed under the Apache License, Version 2.0 (the "License");  
you may not use this file except in compliance with the License.  
You may obtain a copy of the License at  
&nbsp;&nbsp;&nbsp;&nbsp;http://www.apache.org/licenses/LICENSE-2.0  
Unless required by applicable law or agreed to in writing, software  
distributed under the License is distributed on an "AS IS" BASIS,  
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  
See the License for the specific language governing permissions and  
limitations under the License.

# 3D Brain Tumor Segmentation with Swin UNETR (BraTS 21 Challenge)


This tutorial uses the [Swin UNETR](https://arxiv.org/pdf/2201.01266.pdf) [1,2] model for the task of brain tumor segmentation using the [BraTS 21](http://braintumorsegmentation.org/) challenge dataset [3,4,5,6]. Swin UNETR ranked among top-performing models in the BraTS 21 validation phase. The architecture of Swin UNETR is demonstrated below


The following features are included in this tutorial:
1. Transforms for dictionary format data.
1. Define a new transform according to MONAI transform API.
1. Load Nifti image with metadata, load a list of images and stack them.
1. Randomly rotate across each axes for data augmentation.
1. Randomly adjust the intensity for data augmentation.
1. Cache IO and transforms to accelerate training and validation.
1. Swin UNETR model, Dice loss function, Mean Dice metric for brain tumor segmentation task.

For more information access to pre-trained models and distributed training, please refer to Swin UNETR BraTS 21 official repository:

https://github.com/Project-MONAI/research-contributions/tree/main/SwinUNETR/BRATS21

## Data Description

Modality: MRI
Size: 1470 3D volumes (1251 Training + 219 Validation)  
Challenge: RSNA-ASNR-MICCAI Brain Tumor Segmentation (BraTS) Challenge

The dataset needs to be downloaded from the official BraTS 21 challenge portal as in the following

https://www.synapse.org/#!Synapse:syn27046444/wiki/616992

The JSON file containing training and validation sets (internal split) needs to be downloaded from this [link](https://developer.download.nvidia.com/assets/Clara/monai/tutorials/brats21_folds.json) and placed in the same folder as the dataset. As discussed in the following, this tutorial uses fold 1 for training a Swin UNETR model on the BraTS 21 challenge.

### Tumor Characteristics

The sub-regions considered for evaluation in the BraTS 21 challenge are the "enhancing tumor" (ET), the "tumor core" (TC), and the "whole tumor" (WT). The ET is described by areas that show hyper-intensity in T1Gd when compared to T1, but also when compared to “healthy” white matter in T1Gd. The TC describes the bulk of the tumor, which is what is typically resected. The TC entails the ET, as well as the necrotic (NCR) parts of the tumor. The appearance of NCR is typically hypo-intense in T1-Gd when compared to T1. The WT describes the complete extent of the disease, as it entails the TC and the peritumoral edematous/invaded tissue (ED), which is typically depicted by the hyper-intense signal in FLAIR [[BraTS 21]](http://braintumorsegmentation.org/).

The provided segmentation labels have values of 1 for NCR, 2 for ED, 4 for ET, and 0 for everything else.


Figure from [Baid et al.](https://arxiv.org/pdf/2107.02314v1.pdf) [3]



## References


If you find this tutorial helpful, please consider citing [1] and [2]:

[1]: Hatamizadeh, A., Nath, V., Tang, Y., Yang, D., Roth, H. and Xu, D., 2022. Swin UNETR: Swin Transformers for Semantic Segmentation of Brain Tumors in MRI Images. arXiv preprint arXiv:2201.01266.

[2]: Tang, Y., Yang, D., Li, W., Roth, H.R., Landman, B., Xu, D., Nath, V. and Hatamizadeh, A., 2022. Self-supervised pre-training of swin transformers for 3d medical image analysis. In Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (pp. 20730-20740).


### BraTS Dataset References

[3] U.Baid, et al., The RSNA-ASNR-MICCAI BraTS 2021 Benchmark on Brain Tumor Segmentation and Radiogenomic Classification, arXiv:2107.02314, 2021.

[4] B. H. Menze, A. Jakab, S. Bauer, J. Kalpathy-Cramer, K. Farahani, J. Kirby, et al. "The Multimodal Brain Tumor Image Segmentation Benchmark (BRATS)", IEEE Transactions on Medical Imaging 34(10), 1993-2024 (2015) DOI: 10.1109/TMI.2014.2377694

[5] S. Bakas, H. Akbari, A. Sotiras, M. Bilello, M. Rozycki, J.S. Kirby, et al., "Advancing The Cancer Genome Atlas glioma MRI collections with expert segmentation labels and radiomic features", Nature Scientific Data, 4:170117 (2017) DOI: 10.1038/sdata.2017.117

[6] S. Bakas, H. Akbari, A. Sotiras, M. Bilello, M. Rozycki, J. Kirby, et al., "Segmentation Labels and Radiomic Features for the Pre-operative Scans of the TCGA-GBM collection", The Cancer Imaging Archive, 2017. DOI: 10.7937/K9/TCIA.2017.KLXWJJ1Q

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Project-MONAI/tutorials/blob/main/3d_segmentation/swin_unetr_brats21_segmentation_3d.ipynb)

## Swin UNETR Model

The inputs to [Swin UNETR](https://arxiv.org/pdf/2201.01266.pdf) are 3D multi-modal MRI images with 4 channels.
The patch partition block creates non-overlapping patches of the input data and projects them into embedding tokens with a resolution of 128x128x128.
The projected tokens are then encoded by using a 3D [Swin Transformer](https://openaccess.thecvf.com/content/ICCV2021/papers/Liu_Swin_Transformer_Hierarchical_Vision_Transformer_Using_Shifted_Windows_ICCV_2021_paper.pdf) in which the self-attention is computed within local windows.
The interaction between different windows is obtained by using 3D window shifting as illustrated below.


The transformer-based encoder is connected to a CNN-decoder via skip connection at multiple resolutions.
The segmentation output consists of 3 output channels corresponding to ET, WT, and TC sub-regions and is computed by using a 1x1x1 convolutional layer followed by Sigmoid activation function.

## Download dataset and json file

- Register and download the official BraTS 21 dataset from the link below and place them into "TrainingData" in the dataset folder:

  https://www.synapse.org/#!Synapse:syn27046444/wiki/616992
  
  For example, the address of a single file is as follows:
  
  "TrainingData/BraTS2021_01146/BraTS2021_01146_flair.nii.gz"
  

- Download the json file from this [link](https://developer.download.nvidia.com/assets/Clara/monai/tutorials/brats21_folds.json) and placed in the same folder as the dataset.

## Setup environment
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

"""## Setup imports"""

import atexit
import os
import json
import shutil
import sys
import tempfile
import time

import matplotlib

_mpl_backend = os.environ.get("BRATS_MPL_BACKEND", "").strip()
if _mpl_backend:
    matplotlib.use(_mpl_backend)

import matplotlib.pyplot as plt
import numpy as np
import nibabel as nib

from monai.losses import DiceLoss
from monai.inferers import sliding_window_inference
from monai import transforms
from monai.transforms import (
    AsDiscrete,
    Activations,
)

from monai.config import print_config
from monai.metrics import DiceMetric
from monai.utils.enums import MetricReduction
from monai.networks.nets import SwinUNETR
from monai import data
from monai.data import decollate_batch
from functools import partial

import torch


_BRATS_LOG_FP = None


class _TeeTextIO:
    """Duplicate stdout/stderr to a UTF-8 log file (retrievable training transcript)."""

    __slots__ = ("_primary", "_log")

    def __init__(self, primary, log_f):
        self._primary = primary
        self._log = log_f

    def write(self, data):
        self._primary.write(data)
        self._log.write(data)
        return len(data)

    def flush(self):
        self._primary.flush()
        self._log.flush()

    def fileno(self):
        return self._primary.fileno()

    def isatty(self):
        return self._primary.isatty()

    def writable(self):
        return True


def _brats_close_log_file():
    global _BRATS_LOG_FP
    if _BRATS_LOG_FP is not None:
        try:
            _BRATS_LOG_FP.flush()
            _BRATS_LOG_FP.close()
        except Exception:
            pass
        _BRATS_LOG_FP = None


def _brats_setup_file_logging():
    """Mirror all prints to a log file (BRATS_LOG_FILE or checkpoints/logs/...)."""
    global _BRATS_LOG_FP
    if os.environ.get("BRATS_DISABLE_FILE_LOG", "").strip().lower() in ("1", "true", "yes"):
        return
    log_path = os.environ.get("BRATS_LOG_FILE", "").strip()
    if not log_path:
        log_dir = os.environ.get("BRATS_LOG_DIR", "/scratch/users/linika/checkpoints/logs").strip()
        os.makedirs(log_dir, exist_ok=True)
        log_path = os.path.join(
            log_dir, "brats_train_{}.log".format(time.strftime("%Y%m%d_%H%M%S"))
        )
    else:
        os.makedirs(os.path.dirname(os.path.abspath(log_path)) or ".", exist_ok=True)
    _BRATS_LOG_FP = open(log_path, "w", encoding="utf-8", buffering=1)
    atexit.register(_brats_close_log_file)
    sys.stdout = _TeeTextIO(sys.__stdout__, _BRATS_LOG_FP)
    sys.stderr = _TeeTextIO(sys.__stderr__, _BRATS_LOG_FP)
    print("BRATS file logging:", os.path.abspath(log_path), flush=True)


_brats_setup_file_logging()

print_config()

"""## Setup data directory

You can specify a directory with the `MONAI_DATA_DIRECTORY` environment variable.  
This allows you to save results and reuse downloads.  
If not specified a temporary directory will be used.
"""

# Google Colab Drive mount removed — use data_dir on FarmShare scratch (see hyper-parameters cell).



from pathlib import Path


def assert_brats_split_paths_exist(split_path: Path, base: Path) -> None:
    with open(split_path) as f:
        spec = json.load(f)
    missing = []
    for split_name in ("training", "validation"):
        for entry in spec[split_name]:
            for rel in list(entry["image"]) + [entry["label"]]:
                full = base / rel
                if not full.is_file():
                    missing.append(str(full))
    if missing:
        preview = "\n".join(missing[:15])
        raise FileNotFoundError(
            f"{len(missing)} paths from {split_path} are missing (first 15):\n{preview}"
        )
    n_tr, n_va = len(spec["training"]), len(spec["validation"])
    print(
        f"Split JSON validated: {n_tr} train + {n_va} val subjects; "
        f"all listed modality files exist under {base}."
    )


BRATS21_SPLIT_JSON = Path(
    os.environ.get("BRATS21_SPLIT_JSON", "/scratch/users/linika/brats21_80_20.json")
)
if not BRATS21_SPLIT_JSON.is_file():
    raise FileNotFoundError(f"Split list not found: {BRATS21_SPLIT_JSON}")

BRATS_SKIP_TRAIN = os.environ.get("BRATS_SKIP_TRAIN", "").strip().lower() in ("1", "true", "yes")
BRATS_GEN_OVERLAYS = os.environ.get("BRATS_GEN_OVERLAYS", "").strip().lower() in ("1", "true", "yes")

directory = os.environ.get("MONAI_DATA_DIRECTORY")
if directory is not None:
    os.makedirs(directory, exist_ok=True)
root_dir = tempfile.mkdtemp() if directory is None else directory
print(root_dir)

"""## Setup average meter, fold reader, checkpoint saver"""

class AverageMeter(object):
    def __init__(self):
        self.reset()

    def reset(self):
        self.val = 0
        self.avg = 0
        self.sum = 0
        self.count = 0

    def update(self, val, n=1):
        self.val = val
        self.sum += val * n
        self.count += n
        self.avg = np.where(self.count > 0, self.sum / self.count, self.sum)

'''
def datafold_read(datalist, basedir, fold=0, key="training"):
    with open(datalist) as f:
        json_data = json.load(f)

    json_data = json_data[key]

    for d in json_data:
        for k in d:
            if isinstance(d[k], list):
                d[k] = [os.path.join(basedir, iv) for iv in d[k]]
            elif isinstance(d[k], str):
                d[k] = os.path.join(basedir, d[k]) if len(d[k]) > 0 else d[k]

    tr = []
    val = []
    for d in json_data:
        if "fold" in d and d["fold"] == fold:
            val.append(d)
        else:
            tr.append(d)

    return tr, val
'''
def datafold_read(datalist, basedir, fold=None):
    with open(datalist) as f:
        json_data = json.load(f)

    if "validation" in json_data:
        tr = json_data["training"]
        val = json_data["validation"]
    else:
        all_data = json_data["training"]
        tr, val = [], []
        for d in all_data:
            if "fold" in d and d["fold"] == fold:
                val.append(d)
            else:
                tr.append(d)

    for split in [tr, val]:
        for d in split:
            for k in d:
                if isinstance(d[k], list):
                    d[k] = [os.path.join(basedir, iv) for iv in d[k]]
                elif isinstance(d[k], str):
                    d[k] = os.path.join(basedir, d[k]) if len(d[k]) > 0 else d[k]

    return tr, val

def save_checkpoint(model, epoch, filename="model.pt", best_acc=0, dir_add=root_dir):
    state_dict = model.state_dict()
    save_dict = {"epoch": epoch, "best_acc": best_acc, "state_dict": state_dict}
    filename = os.path.join(dir_add, filename)
    torch.save(save_dict, filename)
    print("Saving checkpoint", filename)

"""## Setup dataloader"""

def get_loader(batch_size, data_dir, json_list, fold, roi):
    data_dir = data_dir
    datalist_json = json_list
    train_files, validation_files = datafold_read(datalist=datalist_json, basedir=data_dir, fold=fold)
    train_transform = transforms.Compose(
        [
            transforms.LoadImaged(keys=["image", "label"]),
            transforms.ConvertToMultiChannelBasedOnBratsClassesd(keys="label"),
            transforms.CropForegroundd(
                keys=["image", "label"],
                source_key="image",
                k_divisible=[roi[0], roi[1], roi[2]],
                allow_smaller=True,
            ),
            transforms.RandSpatialCropd(
                keys=["image", "label"],
                roi_size=[roi[0], roi[1], roi[2]],
                random_size=False,
            ),
            transforms.RandFlipd(keys=["image", "label"], prob=0.5, spatial_axis=0),
            transforms.RandFlipd(keys=["image", "label"], prob=0.5, spatial_axis=1),
            transforms.RandFlipd(keys=["image", "label"], prob=0.5, spatial_axis=2),
            transforms.NormalizeIntensityd(keys="image", nonzero=True, channel_wise=True),
            transforms.RandScaleIntensityd(keys="image", factors=0.1, prob=1.0),
            transforms.RandShiftIntensityd(keys="image", offsets=0.1, prob=1.0),
        ]
    )
    val_transform = transforms.Compose(
        [
            transforms.LoadImaged(keys=["image", "label"]),
            transforms.ConvertToMultiChannelBasedOnBratsClassesd(keys="label"),
            transforms.NormalizeIntensityd(keys="image", nonzero=True, channel_wise=True),
        ]
    )

    train_ds = data.Dataset(data=train_files, transform=train_transform)

    train_loader = data.DataLoader(
        train_ds,
        batch_size=batch_size,
        shuffle=True,
        num_workers=2, #8,
        pin_memory=True,
    )
    val_ds = data.Dataset(data=validation_files, transform=val_transform)
    val_loader = data.DataLoader(
        val_ds,
        batch_size=1,
        shuffle=False,
        num_workers=2, #8,
        pin_memory=True,
    )

    return train_loader, val_loader

"""## Set dataset root directory and hyper-parameters

The following hyper-parameters are set for the purpose of this tutorial. However, additional changes, as described below, maybe beneficial.

If GPU memory is not sufficient, reduce sw_batch_size to 2 or batch_size to 1.

Decrease val_every (validation frequency) to 1 for obtaining more accurate checkpoints.
"""

from monai import data

data_dir = "/scratch/users/linika/"
if not BRATS_SKIP_TRAIN:
    assert_brats_split_paths_exist(BRATS21_SPLIT_JSON, Path(data_dir))
json_list = str(BRATS21_SPLIT_JSON)
roi = (128, 128, 128)
batch_size = 1
sw_batch_size = 2
fold = None
infer_overlap = 0.5
if os.environ.get("BRATS_FULL_TRAIN", "").strip().lower() in ("1", "true", "yes"):
    max_epochs = int(os.environ.get("BRATS_MAX_EPOCHS", "100"))
    val_every = int(os.environ.get("BRATS_VAL_EVERY", "5"))
    print(f"Training mode: FULL (max_epochs={max_epochs}, val_every={val_every}).")
else:
    max_epochs = 1
    val_every = 1
    print(
        "Training mode: OOM probe (max_epochs=1, val_every=1). "
        "Set BRATS_FULL_TRAIN=1 to run full training (default max_epochs=100, val_every=5; override with BRATS_MAX_EPOCHS / BRATS_VAL_EVERY)."
    )
if not BRATS_SKIP_TRAIN:
    train_loader, val_loader = get_loader(batch_size, data_dir, json_list, fold, roi)
else:
    train_loader, val_loader = None, None
    print("BRATS_SKIP_TRAIN: skipping JSON path check (except above), DataLoaders, and training.")

import os
CHECKPOINT_DIR = os.environ.get("BRATS_CHECKPOINT_DIR", "/scratch/users/linika/checkpoints")
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

"""## Check data shape and visualize"""

if not BRATS_SKIP_TRAIN:
    img_add = os.path.join(data_dir, "TrainingData/BraTS2021_00006/BraTS2021_00006_flair.nii.gz")
    label_add = os.path.join(data_dir, "TrainingData/BraTS2021_00006/BraTS2021_00006_seg.nii.gz")
    img = nib.load(img_add).get_fdata()
    label = nib.load(label_add).get_fdata()
    print(f"image shape: {img.shape}, label shape: {label.shape}")
    plt.figure("image", (18, 6))
    plt.subplot(1, 2, 1)
    plt.title("image")
    plt.imshow(img[:, :, 78], cmap="gray")
    plt.subplot(1, 2, 2)
    plt.title("label")
    plt.imshow(label[:, :, 78])
    plt.savefig(os.path.join(CHECKPOINT_DIR, "debug_sample_slice.png"), dpi=120, bbox_inches="tight")
    plt.close()

"""## Create Swin UNETR model

In this section, we create Swin UNETR model for the 3-class brain tumor semantic segmentation. We use a feature size of 48. We also use gradient checkpointing (use_checkpoint) for more memory-efficient training. However, use_checkpoint for faster training if enough GPU memory is available.  
"""

os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("=" * 60)
print("Training device:", device)
print("torch.cuda.is_available():", torch.cuda.is_available())
if torch.cuda.is_available():
    i = torch.cuda.current_device()
    print("CUDA device index:", i)
    print("CUDA device name:", torch.cuda.get_device_name(i))
print("=" * 60)
if os.environ.get("REQUIRE_CUDA", "").strip().lower() in ("1", "true", "yes"):
    if not torch.cuda.is_available():
        raise RuntimeError(
            "REQUIRE_CUDA is set but no GPU is visible. "
            "Request a GPU (e.g. srun --partition=gpu --gres=gpu:1 ...) and retry."
        )

model = SwinUNETR(
    in_channels=4,
    out_channels=3,
    feature_size=48,
    drop_rate=0.0,
    attn_drop_rate=0.0,
    dropout_path_rate=0.0,
    use_checkpoint=True,
).to(device)

"""## Optimizer and loss function"""

torch.backends.cudnn.benchmark = True
dice_loss = DiceLoss(to_onehot_y=False, sigmoid=True)
post_sigmoid = Activations(sigmoid=True)
post_pred = AsDiscrete(argmax=False, threshold=0.5)
dice_acc = DiceMetric(include_background=True, reduction=MetricReduction.MEAN_BATCH, get_not_nans=True)
model_inferer = partial(
    sliding_window_inference,
    roi_size=[roi[0], roi[1], roi[2]],
    sw_batch_size=sw_batch_size,
    predictor=model,
    overlap=infer_overlap,
)

optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-5)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=max_epochs)

start_epoch = 0
_finetune_only = os.environ.get("BRATS_FINETUNE_ONLY", "").strip().lower() in ("1", "true", "yes")
_resume_path = os.environ.get("BRATS_RESUME_CHECKPOINT", "").strip()
if not _resume_path and os.environ.get("BRATS_RESUME", "").strip().lower() in ("1", "true", "yes"):
    _fe = os.environ.get("BRATS_RESUME_FILE_EPOCH", "10").strip() or "10"
    _resume_path = os.path.join(CHECKPOINT_DIR, f"model_epoch_{_fe}.pth")
if _resume_path:
    if os.path.isfile(_resume_path):
        try:
            _ck = torch.load(_resume_path, map_location=device, weights_only=False)
        except TypeError:
            _ck = torch.load(_resume_path, map_location=device)
        model.load_state_dict(_ck["model_state_dict"])
        if _finetune_only:
            start_epoch = 0
            print(
                f"Finetune-only: loaded weights from {_resume_path!r}; "
                f"fresh optimizer/scheduler; training epochs 0..{max_epochs - 1}"
            )
        else:
            if "optimizer_state_dict" in _ck:
                optimizer.load_state_dict(_ck["optimizer_state_dict"])
            if "scheduler_state_dict" in _ck:
                scheduler.load_state_dict(_ck["scheduler_state_dict"])
            start_epoch = int(_ck.get("epoch", 0))
            print(
                f"Loaded resume checkpoint {_resume_path!r} — next training epoch index: {start_epoch}"
            )
    else:
        print(f"Warning: BRATS resume file missing ({_resume_path}); training from epoch 0.")

"""## Define Train and Validation Epoch"""


def save_prediction_overlay_figures(
    checkpoint_path: str,
    data_dir: str,
    case_num: str,
    out_dir: str,
    device: torch.device,
    roi_size,
    sw_bs: int = 1,
    overlap: float = 0.5,
) -> None:
    """Save FLAIR / GT / pred / overlay PNG for one BraTS case (axial middle slice)."""
    os.makedirs(out_dir, exist_ok=True)
    case_id = f"BraTS2021_{case_num}"
    test_files = [
        {
            "image": [
                os.path.join(data_dir, f"TrainingData/{case_id}/{case_id}_flair.nii.gz"),
                os.path.join(data_dir, f"TrainingData/{case_id}/{case_id}_t1ce.nii.gz"),
                os.path.join(data_dir, f"TrainingData/{case_id}/{case_id}_t1.nii.gz"),
                os.path.join(data_dir, f"TrainingData/{case_id}/{case_id}_t2.nii.gz"),
            ],
            "label": os.path.join(data_dir, f"TrainingData/{case_id}/{case_id}_seg.nii.gz"),
        }
    ]
    test_transform = transforms.Compose(
        [
            transforms.LoadImaged(keys=["image", "label"]),
            transforms.ConvertToMultiChannelBasedOnBratsClassesd(keys="label"),
            transforms.NormalizeIntensityd(keys="image", nonzero=True, channel_wise=True),
        ]
    )
    test_ds = data.Dataset(data=test_files, transform=test_transform)
    test_loader = data.DataLoader(
        test_ds, batch_size=1, shuffle=False, num_workers=2, pin_memory=True
    )
    seg_model = SwinUNETR(
        in_channels=4,
        out_channels=3,
        feature_size=48,
        drop_rate=0.0,
        attn_drop_rate=0.0,
        dropout_path_rate=0.0,
        use_checkpoint=False,
    ).to(device)
    ckpt = torch.load(checkpoint_path, map_location=device, weights_only=False)
    seg_model.load_state_dict(ckpt["model_state_dict"])
    seg_model.eval()
    inferer = partial(
        sliding_window_inference,
        roi_size=[roi_size[0], roi_size[1], roi_size[2]],
        sw_batch_size=sw_bs,
        predictor=seg_model,
        overlap=overlap,
    )
    with torch.no_grad():
        for batch_data in test_loader:
            image = batch_data["image"].to(device)
            prob = torch.sigmoid(inferer(image))
            seg = prob[0].detach().cpu().numpy()
            seg = (seg > 0.5).astype(np.int8)
            seg_out = np.zeros((seg.shape[1], seg.shape[2], seg.shape[3]), dtype=np.int16)
            seg_out[seg[1] == 1] = 2
            seg_out[seg[0] == 1] = 1
            seg_out[seg[2] == 1] = 4

    flair_path = os.path.join(data_dir, f"TrainingData/{case_id}/{case_id}_flair.nii.gz")
    label_path = os.path.join(data_dir, f"TrainingData/{case_id}/{case_id}_seg.nii.gz")
    flair = nib.load(flair_path).get_fdata()
    gt = nib.load(label_path).get_fdata()
    z = flair.shape[2] // 2
    f_sl = np.asarray(flair[:, :, z], dtype=np.float64)
    f_sl = (f_sl - np.min(f_sl)) / (np.ptp(f_sl) + 1e-8)
    gt_sl = gt[:, :, z].astype(np.float64)
    pr_sl = seg_out[:, :, z].astype(np.float64)

    overlay = np.stack([f_sl, f_sl, f_sl], axis=-1)
    ed = pr_sl == 2
    nc = pr_sl == 1
    et = pr_sl == 4
    overlay[..., 0] = np.where(et, 0.82 * overlay[..., 0] + 0.18 * 1.0, overlay[..., 0])
    overlay[..., 1] = np.where(ed, 0.72 * overlay[..., 1] + 0.28 * 1.0, overlay[..., 1])
    overlay[..., 2] = np.where(nc, 0.72 * overlay[..., 2] + 0.28 * 1.0, overlay[..., 2])
    overlay = np.clip(overlay, 0, 1)

    fig, axes = plt.subplots(1, 4, figsize=(16, 4))
    axes[0].imshow(f_sl, cmap="gray")
    axes[0].set_title("FLAIR")
    axes[0].axis("off")
    axes[1].imshow(gt_sl)
    axes[1].set_title("Ground truth")
    axes[1].axis("off")
    axes[2].imshow(pr_sl, vmin=0, vmax=4)
    axes[2].set_title("Prediction")
    axes[2].axis("off")
    axes[3].imshow(overlay)
    axes[3].set_title("Overlay on FLAIR")
    axes[3].axis("off")
    fig.suptitle(f"{case_id}  z={z}  {os.path.basename(checkpoint_path)}")
    fig.tight_layout()
    out_png = os.path.join(out_dir, f"overlay_{case_id}_z{z}.png")
    fig.savefig(out_png, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Wrote overlay figure: {out_png}")


def train_epoch(model, loader, optimizer, epoch, loss_func):
    model.train()
    start_time = time.time()
    run_loss = AverageMeter()
    for idx, batch_data in enumerate(loader):
        optimizer.zero_grad(set_to_none=True)
        data, target = batch_data["image"].to(device), batch_data["label"].to(device)
        logits = model(data)
        loss = loss_func(logits, target)
        loss.backward()
        optimizer.step()
        run_loss.update(loss.item(), n=batch_size)
        print(
            "Epoch {}/{} {}/{}".format(epoch, max_epochs, idx, len(loader)),
            "loss: {:.4f}".format(run_loss.avg),
            "time {:.2f}s".format(time.time() - start_time),
        )
        start_time = time.time()
    return run_loss.avg


def val_epoch(
    model,
    loader,
    epoch,
    acc_func,
    model_inferer=None,
    post_sigmoid=None,
    post_pred=None,
):
    model.eval()
    start_time = time.time()
    run_acc = AverageMeter()

    with torch.no_grad():
        for idx, batch_data in enumerate(loader):
            data, target = batch_data["image"].to(device), batch_data["label"].to(device)
            logits = model_inferer(data)
            val_labels_list = decollate_batch(target)
            val_outputs_list = decollate_batch(logits)
            val_output_convert = [post_pred(post_sigmoid(val_pred_tensor)) for val_pred_tensor in val_outputs_list]
            acc_func.reset()
            acc_func(y_pred=val_output_convert, y=val_labels_list)
            acc, not_nans = acc_func.aggregate()
            run_acc.update(acc.cpu().numpy(), n=not_nans.cpu().numpy())
            dice_tc = run_acc.avg[0]
            dice_wt = run_acc.avg[1]
            dice_et = run_acc.avg[2]
            print(
                "Val {}/{} {}/{}".format(epoch, max_epochs, idx, len(loader)),
                ", dice_tc:",
                dice_tc,
                ", dice_wt:",
                dice_wt,
                ", dice_et:",
                dice_et,
                ", time {:.2f}s".format(time.time() - start_time),
            )
            start_time = time.time()

    return run_acc.avg

"""## Define Trainer"""

def trainer(
    model,
    train_loader,
    val_loader,
    optimizer,
    loss_func,
    acc_func,
    scheduler,
    model_inferer=None,
    start_epoch=0,
    post_sigmoid=None,
    post_pred=None,
):
    val_acc_max = 0.0
    dices_tc = []
    dices_wt = []
    dices_et = []
    dices_avg = []
    loss_epochs = []
    trains_epoch = []
    for epoch in range(start_epoch, max_epochs):
        print(time.ctime(), "Epoch:", epoch)
        epoch_time = time.time()
        train_loss = train_epoch(
            model,
            train_loader,
            optimizer,
            epoch=epoch,
            loss_func=loss_func,
        )
        print(
            "Final training  {}/{}".format(epoch, max_epochs - 1),
            "loss: {:.4f}".format(train_loss),
            "time {:.2f}s".format(time.time() - epoch_time),
        )

        if (epoch + 1) % val_every == 0 or epoch == 0:
            loss_epochs.append(train_loss)
            trains_epoch.append(int(epoch))
            epoch_time = time.time()
            val_acc = val_epoch(
                model,
                val_loader,
                epoch=epoch,
                acc_func=acc_func,
                model_inferer=model_inferer,
                post_sigmoid=post_sigmoid,
                post_pred=post_pred,
            )
            dice_tc = val_acc[0]
            dice_wt = val_acc[1]
            dice_et = val_acc[2]
            val_avg_acc = np.mean(val_acc)
            ckpt_path = os.path.join(CHECKPOINT_DIR, f"model_epoch_{epoch+1}.pth")
            torch.save({
                "epoch": epoch + 1,
                "model_state_dict": model.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "scheduler_state_dict": scheduler.state_dict(),
                "val_acc": val_avg_acc,
            }, ckpt_path)

            print(f"Saved checkpoint: {ckpt_path}")
            print(
                "Final validation stats {}/{}".format(epoch, max_epochs - 1),
                ", dice_tc:",
                dice_tc,
                ", dice_wt:",
                dice_wt,
                ", dice_et:",
                dice_et,
                ", Dice_Avg:",
                val_avg_acc,
                ", time {:.2f}s".format(time.time() - epoch_time),
            )
            dices_tc.append(dice_tc)
            dices_wt.append(dice_wt)
            dices_et.append(dice_et)
            dices_avg.append(val_avg_acc)
            if val_avg_acc > val_acc_max:
                print("new best ({:.6f} --> {:.6f}). ".format(val_acc_max, val_avg_acc))
                val_acc_max = val_avg_acc
                save_checkpoint(
                    model,
                    epoch,
                    best_acc=val_acc_max,
                )
            scheduler.step()
    print("Training Finished !, Best Accuracy: ", val_acc_max)
    return (
        val_acc_max,
        dices_tc,
        dices_wt,
        dices_et,
        dices_avg,
        loss_epochs,
        trains_epoch,
    )

def _plot_training_curves(trains_epoch, loss_epochs, dices_tc, dices_wt, dices_et, dices_avg):
    plt.figure("train", (12, 6))
    plt.subplot(1, 2, 1)
    plt.title("Epoch Average Loss")
    plt.xlabel("epoch")
    plt.plot(trains_epoch, loss_epochs, color="red")
    plt.subplot(1, 2, 2)
    plt.title("Val Mean Dice")
    plt.xlabel("epoch")
    plt.plot(trains_epoch, dices_avg, color="green")
    plt.savefig(
        os.path.join(CHECKPOINT_DIR, "train_curves_loss_dice.png"),
        dpi=150,
        bbox_inches="tight",
    )
    plt.close()
    plt.figure("train", (18, 6))
    plt.subplot(1, 3, 1)
    plt.title("Val Mean Dice TC")
    plt.xlabel("epoch")
    plt.plot(trains_epoch, dices_tc, color="blue")
    plt.subplot(1, 3, 2)
    plt.title("Val Mean Dice WT")
    plt.xlabel("epoch")
    plt.plot(trains_epoch, dices_wt, color="brown")
    plt.subplot(1, 3, 3)
    plt.title("Val Mean Dice ET")
    plt.xlabel("epoch")
    plt.plot(trains_epoch, dices_et, color="purple")
    plt.savefig(
        os.path.join(CHECKPOINT_DIR, "train_curves_per_structure.png"),
        dpi=150,
        bbox_inches="tight",
    )
    plt.close()


"""## Execute training"""

if not BRATS_SKIP_TRAIN:
    (
        val_acc_max,
        dices_tc,
        dices_wt,
        dices_et,
        dices_avg,
        loss_epochs,
        trains_epoch,
    ) = trainer(
        model=model,
        train_loader=train_loader,
        val_loader=val_loader,
        optimizer=optimizer,
        loss_func=dice_loss,
        acc_func=dice_acc,
        scheduler=scheduler,
        model_inferer=model_inferer,
        start_epoch=start_epoch,
        post_sigmoid=post_sigmoid,
        post_pred=post_pred,
    )

    print(f"train completed, best average dice: {val_acc_max:.4f} ")

    _stage = os.environ.get("BRATS_CURRICULUM_STAGE", "").strip()
    if _stage and dices_tc:
        _summary = {
            "stage": _stage,
            "split_json": str(BRATS21_SPLIT_JSON),
            "n_train": len(train_loader.dataset),
            "n_val": len(val_loader.dataset),
            "max_epochs": max_epochs,
            "val_every": val_every,
            "best_dice_avg": float(val_acc_max),
            "final_dice_tc": float(dices_tc[-1]),
            "final_dice_wt": float(dices_wt[-1]),
            "final_dice_et": float(dices_et[-1]),
            "final_dice_avg": float(dices_avg[-1]),
            "val_epochs": [int(e) for e in trains_epoch],
            "dice_tc": [float(x) for x in dices_tc],
            "dice_wt": [float(x) for x in dices_wt],
            "dice_et": [float(x) for x in dices_et],
            "dice_avg": [float(x) for x in dices_avg],
        }
        _out = os.path.join(CHECKPOINT_DIR, "curriculum_dice.json")
        with open(_out, "w", encoding="utf-8") as _f:
            json.dump(_summary, _f, indent=2)
        print(f"Wrote curriculum Dice summary: {_out}")

    """### Plot the loss and Dice metric"""

    if os.environ.get("BRATS_SKIP_PLOTS", "").strip().lower() in ("1", "true", "yes"):
        print("BRATS_SKIP_PLOTS: skipping training curve figures.")
    else:
        _plot_training_curves(
            trains_epoch, loss_epochs, dices_tc, dices_wt, dices_et, dices_avg
        )
else:
    val_acc_max = 0.0
    dices_tc = []
    dices_wt = []
    dices_et = []
    dices_avg = []
    loss_epochs = []
    trains_epoch = []

"""## Optional: prediction overlay figures (set BRATS_GEN_OVERLAYS=1)"""

if BRATS_GEN_OVERLAYS:
    _oc = os.environ.get(
        "BRATS_OVERLAY_CHECKPOINT",
        os.path.join(CHECKPOINT_DIR, "model_epoch_10.pth"),
    ).strip()
    _ocase = os.environ.get("BRATS_OVERLAY_CASE", "01619").strip()
    _ood = os.environ.get(
        "BRATS_OVERLAY_OUTDIR", os.path.join(CHECKPOINT_DIR, "overlays")
    ).strip()
    if os.path.isfile(_oc):
        save_prediction_overlay_figures(
            checkpoint_path=_oc,
            data_dir=data_dir,
            case_num=_ocase,
            out_dir=_ood,
            device=device,
            roi_size=roi,
            sw_bs=1,
            overlap=0.6,
        )
    else:
        print(f"BRATS_GEN_OVERLAYS: checkpoint not found, skip overlays: {_oc}")

"""## Cleanup data directory

Remove directory if a temporary was used.
"""

if directory is None:
    shutil.rmtree(root_dir)